# Generated by Django 4.2.3 on 2023-07-25 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
